services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: presta
      #MYSQL_ROOT_HOST: localhost
      #MYSQL_USER: root
      #MYSQL_ALLOW_EMPTY_PASSWORD: true
#    volumes:
#    - ./presta/db:/docker-entrypoint-initdb.d
#    command: bash -c "sleep 20 && tree && mysql -uroot -proot presta < /dump/db.sql && tail -F /dev/null"
    ports:
      - "9906:3306"
    networks:
      static-network:
        ipv4_address: 192.168.123.10
  web:
    build:
      context: .
      dockerfile: extentions
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
    networks:
      static-network:
        ipv4_address: 192.168.123.20
    command: bash -c "sleep 20 && source /etc/apache2/envvars && /usr/sbin/apache2 && chmod -R 777 presta && tail -F /dev/null"
  dbinit:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    volumes:
      - ./db/backup.sql:/dump/backup.sql
    command:  bash -c "sleep 30 && echo start && mysql -h192.168.123.10 -uroot -proot presta < /dump/backup.sql && echo koniec"
    networks:
      static-network:
        ipv4_address: 192.168.123.30

networks:
  static-network:
    ipam:
      config:
        - subnet: 192.168.123.0/24

