<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUe7abef\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUe7abef/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUe7abef.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUe7abef\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUe7abef\appProdProjectContainer([
    'container.build_hash' => 'Ue7abef',
    'container.build_id' => 'e6a36402',
    'container.build_time' => 1610448777,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUe7abef');
